import edu.rit.ds.RemoteEvent;

/**
 * Class ServerEvent encapsulates a remote event generated by a MQServer in the
 * MQ system. The server events are used to report serverName and the count of
 * incoming/outgoing messages to the log programs.
 */
public class ServerEvent extends RemoteEvent {
	public final String serverName;
	public final int incoming;
	public final int outgoing;

	/**
	 * Create a new Server event.
	 * 
	 * @param serverName
	 *            The name of the MQServer
	 * @param incoming
	 *            The count of incoming messages on the MQServer.
	 * @param outgoing
	 *            The count of outgoing messages from the MQServer
	 */
	public ServerEvent(String serverName, int incoming, int outgoing) {
		this.serverName = serverName;
		this.incoming = incoming;
		this.outgoing = outgoing;
	}
}